package nginx

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/25743/cloud-relay-platform/apps/server-api/internal/store"
	"github.com/25743/cloud-relay-platform/packages/protocol/types"
)

type Manager struct {
	configDir string
	certDir   string
	nginxBin  string
	store     store.Store
}

func NewManager(configDir, certDir, nginxBin string, s store.Store) *Manager {
	return &Manager{
		configDir: configDir,
		certDir:   certDir,
		nginxBin:  nginxBin,
		store:     s,
	}
}

func (m *Manager) RegenerateConfig(ctx context.Context) error {
	tunnels, err := m.store.ListTunnels(ctx, store.TunnelFilter{Status: "active"})
	if err != nil {
		return fmt.Errorf("nginx: list tunnels: %w", err)
	}

	// Collect domain tunnels with their user IDs
	type domainEntry struct {
		tunnel types.TunnelSpec
		cert   *types.CertificateSpec
	}
	var entries []domainEntry

	for _, t := range tunnels {
		if t.Type != "http" && t.Type != "https" {
			continue
		}
		domain := strings.ToLower(strings.TrimSpace(t.Domain))
		if domain == "" {
			continue
		}

		entry := domainEntry{tunnel: t}

		// Look up certificate by domain (domain is globally unique in DNS)
		cert, _ := m.store.FindCertificateByDomain(ctx, domain)
		entry.cert = cert

		entries = append(entries, entry)
	}

	// Step 1: Clear all cert files (avoid accumulation)
	entries2, _ := os.ReadDir(m.certDir)
	for _, e := range entries2 {
		if !e.IsDir() && (strings.HasSuffix(e.Name(), ".crt") || strings.HasSuffix(e.Name(), ".key")) {
			os.Remove(filepath.Join(m.certDir, e.Name()))
		}
	}

	// Step 2: Write only needed cert files
	for _, entry := range entries {
		if entry.cert == nil {
			continue
		}
		os.WriteFile(filepath.Join(m.certDir, entry.cert.ID+".crt"), []byte(entry.cert.CertPEM), 0644)
		os.WriteFile(filepath.Join(m.certDir, entry.cert.ID+".key"), []byte(entry.cert.KeyPEM), 0600)
	}

	// Step 3: Generate nginx config
	var sb strings.Builder
	sb.WriteString("# Auto-generated by 驻阡陌 — do not edit manually\n")

	for _, entry := range entries {
		domain := strings.ToLower(strings.TrimSpace(entry.tunnel.Domain))
		if domain == "" {
			continue
		}

		if entry.tunnel.Type == "https" && entry.cert != nil {
			// HTTPS with SSL certificate
			sb.WriteString(fmt.Sprintf(`
server {
    listen 80;
    listen [::]:80;
    server_name %s;
    location /.well-known/acme-challenge/ {
        root /www/server/nginx/html;
    }
    location / {
        return 301 https://%s$request_uri;
    }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name %s;
    ssl_certificate %s/%s.crt;
    ssl_certificate_key %s/%s.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_timeout 10m;
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_pass http://127.0.0.1:9095;
    }
}
`, domain, domain, domain, m.certDir, entry.cert.ID, m.certDir, entry.cert.ID))
		} else {
			// HTTP or HTTPS without cert — plain HTTP reverse proxy
			sb.WriteString(fmt.Sprintf(`
server {
    listen 80;
    listen [::]:80;
    server_name %s;
    location /.well-known/acme-challenge/ {
        root /www/server/nginx/html;
    }
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:9095;
    }
}
`, domain))
			if entry.tunnel.Type == "https" && entry.cert == nil {
				log.Printf("nginx: HTTPS tunnel %s has domain %s but no SSL certificate — generating HTTP-only config", entry.tunnel.ID, domain)
			}
		}
	}

	confPath := filepath.Join(m.configDir, "domains.conf")
	if err := os.WriteFile(confPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("nginx: write config: %w", err)
	}

	// Step 4: Test and reload nginx
	if m.nginxBin != "" {
		if output, err := exec.Command(m.nginxBin, "-t").CombinedOutput(); err != nil {
			log.Printf("nginx: config test failed: %s", string(output))
			return fmt.Errorf("nginx: config test failed: %s", string(output))
		}
		if output, err := exec.Command(m.nginxBin, "-s", "reload").CombinedOutput(); err != nil {
			log.Printf("nginx: reload failed: %s", string(output))
			return fmt.Errorf("nginx: reload failed: %s", string(output))
		}
		log.Printf("nginx: config regenerated and reloaded (%d domain tunnels)", len(entries))
	}

	return nil
}
