package nginx

import (
	"bytes"
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"log"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/25743/cloud-relay-platform/apps/cert-keeper-api/internal/store"
)

type Manager struct {
	configDir      string
	certDir        string
	nginxBin       string
	store          store.Store
	publicIP       string
	defaultBackend string
	domainBackends map[string]string
	skipDomains    map[string]bool
}

func NewManager(configDir, certDir, nginxBin string, s store.Store, publicIP string) *Manager {
	return &Manager{
		configDir:      configDir,
		certDir:        certDir,
		nginxBin:       nginxBin,
		store:          s,
		publicIP:       publicIP,
		defaultBackend: "http://127.0.0.1:9095",
		domainBackends: make(map[string]string),
		skipDomains:    make(map[string]bool),
	}
}

// SetDomainBackends configures per-domain proxy_pass targets.
// Format: "domain1=http://host:port,domain2=http://host:port"
func (m *Manager) SetDomainBackends(mapping string) {
	for _, entry := range strings.Split(mapping, ",") {
		entry = strings.TrimSpace(entry)
		if entry == "" {
			continue
		}
		parts := strings.SplitN(entry, "=", 2)
		if len(parts) != 2 {
			continue
		}
		domain := strings.ToLower(strings.TrimSpace(parts[0]))
		backend := strings.TrimSpace(parts[1])
		if domain != "" && backend != "" {
			m.domainBackends[domain] = backend
		}
	}
}

func (m *Manager) backendFor(domain string) string {
	if backend, ok := m.domainBackends[strings.ToLower(domain)]; ok {
		return backend
	}
	return m.defaultBackend
}

// SetSkipDomains configures domains whose server blocks should NOT be
// generated (cert files are still written so external configs can reference them).
// Format: "domain1,domain2"
func (m *Manager) SetSkipDomains(list string) {
	for _, d := range strings.Split(list, ",") {
		d = strings.ToLower(strings.TrimSpace(d))
		if d != "" {
			m.skipDomains[d] = true
		}
	}
}

func (m *Manager) RegenerateConfig(ctx context.Context) error {
	if err := os.MkdirAll(m.certDir, 0o755); err != nil {
		return fmt.Errorf("nginx: ensure cert dir: %w", err)
	}
	if err := os.MkdirAll(m.configDir, 0o755); err != nil {
		return fmt.Errorf("nginx: ensure config dir: %w", err)
	}

	certs, err := m.store.ListAllCertificates(ctx)
	if err != nil {
		return fmt.Errorf("nginx: list certs: %w", err)
	}

	entries, err := os.ReadDir(m.certDir)
	if err != nil {
		return fmt.Errorf("nginx: read cert dir: %w", err)
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".crt") && !strings.HasSuffix(name, ".key") {
			continue
		}
		if err := os.Remove(filepath.Join(m.certDir, name)); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("nginx: remove stale cert file %s: %w", name, err)
		}
	}

	for _, cert := range certs {
		if err := writeFileAtomic(filepath.Join(m.certDir, cert.ID+".crt"), []byte(cert.CertPEM), 0o644); err != nil {
			return fmt.Errorf("nginx: write cert for %s: %w", cert.Domain, err)
		}
		if err := writeFileAtomic(filepath.Join(m.certDir, cert.ID+".key"), []byte(cert.KeyPEM), 0o600); err != nil {
			return fmt.Errorf("nginx: write key for %s: %w", cert.Domain, err)
		}
	}

	confPath := filepath.Join(m.configDir, "cert-domains.conf")
	if err := writeFileAtomic(confPath, []byte(m.buildConfig(certs)), 0o644); err != nil {
		return fmt.Errorf("nginx: write config: %w", err)
	}

	if m.nginxBin != "" {
		if output, err := m.runNginxCommand(ctx, "-t"); err != nil {
			log.Printf("nginx: config test failed: %s", output)
			return fmt.Errorf("nginx: config test failed: %s", output)
		}
		if output, err := m.runNginxCommand(ctx, "-s", "reload"); err != nil {
			log.Printf("nginx: reload failed: %s", output)
			return fmt.Errorf("nginx: reload failed: %s", output)
		}
		// Wait for nginx workers to pick up the new configuration.
		// nginx -s reload is async: the master signals old workers to
		// gracefully shut down and spawns new ones with the new config.
		time.Sleep(2 * time.Second)
		log.Printf("nginx: cert-keeper config regenerated (%d domains)", len(certs))
	}

	return nil
}

func (m *Manager) buildConfig(certs []store.Certificate) string {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by 证书管家 — do not edit manually\n")

	for _, cert := range certs {
		domain := strings.ToLower(strings.TrimSpace(cert.Domain))
		if domain == "" || m.skipDomains[domain] {
			continue
		}

		sb.WriteString(fmt.Sprintf(`
server {
    listen 80;
    listen [::]:80;
    server_name %s;
    location /.well-known/acme-challenge/ {
        root /www/server/nginx/html;
    }
    location / {
        return 301 https://%s$request_uri;
    }
}
`, domain, domain))

		sb.WriteString(fmt.Sprintf(`
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name %s;
    ssl_certificate %s/%s.crt;
    ssl_certificate_key %s/%s.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_timeout 10m;
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header Forwarded "for=$remote_addr;proto=https;host=$host";
        proxy_pass %s;
    }
}
`, domain, m.certDir, cert.ID, m.certDir, cert.ID, m.backendFor(domain)))
	}

	return sb.String()
}

func (m *Manager) VerifyCertificates(ctx context.Context, certs []store.Certificate) error {
	if m.nginxBin == "" {
		return nil
	}

	activeConfig, err := m.loadActiveConfig(ctx)
	if err != nil {
		return err
	}

	includeLine := fmt.Sprintf("include %s/*.conf;", filepath.ToSlash(m.configDir))
	if !strings.Contains(activeConfig, includeLine) {
		return fmt.Errorf("nginx: active config missing include %q", includeLine)
	}

	for _, cert := range certs {
		domain := strings.ToLower(strings.TrimSpace(cert.Domain))
		if domain == "" || m.skipDomains[domain] {
			continue
		}
		serverNameLine := fmt.Sprintf("server_name %s;", domain)
		if !strings.Contains(activeConfig, serverNameLine) {
			return fmt.Errorf("nginx: active config missing %q", serverNameLine)
		}
		certPath := filepath.Join(m.certDir, cert.ID+".crt")
		certLine := fmt.Sprintf("ssl_certificate %s;", filepath.ToSlash(certPath))
		if !strings.Contains(activeConfig, certLine) {
			return fmt.Errorf("nginx: active config missing %q", certLine)
		}
		expectedPEM, err := os.ReadFile(certPath)
		if err != nil {
			return fmt.Errorf("nginx: read expected cert for %s: %w", domain, err)
		}
		if err := m.verifyServedCertificate(ctx, domain, expectedPEM); err != nil {
			return fmt.Errorf("nginx: live TLS verification failed for %s: %w", domain, err)
		}
	}

	return nil
}

func (m *Manager) loadActiveConfig(ctx context.Context) (string, error) {
	output, err := m.runNginxCommand(ctx, "-T")
	if err != nil {
		return "", fmt.Errorf("nginx: dump active config failed: %s", output)
	}
	return output, nil
}

func (m *Manager) runNginxCommand(ctx context.Context, args ...string) (string, error) {
	output, err := exec.CommandContext(ctx, m.nginxBin, args...).CombinedOutput()
	return strings.TrimSpace(string(output)), err
}

func (m *Manager) verifyServedCertificate(ctx context.Context, domain string, expectedPEM []byte) error {
	expectedCert, err := parseLeafCertificate(expectedPEM)
	if err != nil {
		return fmt.Errorf("parse expected certificate: %w", err)
	}

	dialer := &net.Dialer{}
	rawConn, err := dialer.DialContext(ctx, "tcp", "127.0.0.1:443")
	if err != nil {
		return fmt.Errorf("dial local nginx: %w", err)
	}

	tlsConn := tls.Client(rawConn, &tls.Config{
		ServerName:         domain,
		InsecureSkipVerify: true,
		MinVersion:         tls.VersionTLS12,
	})
	defer tlsConn.Close()

	deadline := time.Now().Add(5 * time.Second)
	if ctxDeadline, ok := ctx.Deadline(); ok {
		deadline = ctxDeadline
	}
	if err := tlsConn.SetDeadline(deadline); err != nil {
		return fmt.Errorf("set TLS deadline: %w", err)
	}
	if err := tlsConn.HandshakeContext(ctx); err != nil {
		return fmt.Errorf("TLS handshake: %w", err)
	}

	state := tlsConn.ConnectionState()
	if len(state.PeerCertificates) == 0 {
		return fmt.Errorf("no peer certificate served")
	}
	leaf := state.PeerCertificates[0]
	if err := leaf.VerifyHostname(domain); err != nil {
		return fmt.Errorf("served certificate CN=%q DNS=%v: %w", leaf.Subject.CommonName, leaf.DNSNames, err)
	}
	if !bytes.Equal(leaf.Raw, expectedCert.Raw) {
		return fmt.Errorf("served certificate fingerprint does not match expected certificate for %s", domain)
	}
	return nil
}

func parseLeafCertificate(certPEM []byte) (*x509.Certificate, error) {
	block, _ := pem.Decode(certPEM)
	if block == nil {
		return nil, fmt.Errorf("no PEM block found")
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, err
	}
	return cert, nil
}

func writeFileAtomic(path string, data []byte, perm os.FileMode) (err error) {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp-")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	closed := false
	defer func() {
		if !closed {
			_ = tmp.Close()
		}
		if err != nil {
			_ = os.Remove(tmpPath)
		}
	}()

	if _, err = tmp.Write(data); err != nil {
		return err
	}
	if err = tmp.Chmod(perm); err != nil {
		return err
	}
	if err = tmp.Close(); err != nil {
		return err
	}
	closed = true
	if err = os.Rename(tmpPath, path); err != nil {
		return err
	}
	return nil
}
